@extends('layouts.frontEnd')
@section('content')

    <div class="expert-section gray-bg breadcrumb-area" style="background: url('{{ asset('assets/images') }}/{{ $basic->breadcrumb }}');">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-xs-12">
                    <h3 class="breadcrumb-title">{{ $page_title }}</h3>
                    <div class="breadcrumb-wrap">
                        <ul class="breadcrumb-list">
                            <li><a href="{{ route('home') }}">Home </a></li>
                            <li><a href="#">{{ $page_title }} </a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="expert-section gray-bg">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="area-heading text-center">
                        <h2 class="area-title">Términos y Condiciones de Uso del Sitio Web Signals CLUB</h2>
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-md-12" style="text-align:justify">
                    {!! $basic->terms !!}
<!--                    <h5>Última actualización: 05/11/2018</h5>-->
<!--                    <p>-->
<!--                       Los siguientes términos y condiciones (los "Términos y Condiciones") rigen el uso que usted le dé a este sitio web y a cualquiera de los contenidos disponibles por o a través de este sitio web, incluyendo cualquier contenido derivado del mismo (el "Sitio Web") ("Signals CLUB." o "nosotros") ha puesto a su disposición el Sitio Web. Podemos cambiar los Términos y Condiciones de vez en cuando, en cualquier momento sin ninguna notificación, sólo publicando los cambios en el Sitio Web. AL USAR EL SITIO WEB, USTED ACEPTA Y ESTÉ DE ACUERDO CON ESTOS TÉRMINOS Y CONDICIONES EN LO QUE SE REFIERE A SU USO DEL SITIO WEB. Si usted no está de acuerdo con estos Términos y Condiciones, no puede tener acceso al mismo ni usar el Sitio Web de ninguna otra manera.-->
                       
<!--                       <ul>-->
<!--                           <li><span style="font-weight:bold">1. Derechos de Propiedad.</span> Entre usted y Signals CLUB., Signals CLUB. es dueño único y exclusivo, de todos los derechos, título e intereses en y del Sitio Web (Códigos internos e imagen de marca) más no es ni responsable ni dueño de las opiniones o análisis que los usuarios realicen en la página.</li><br>-->
<!--                           <li><span style="font-weight:bold">2. Licencia Limitada.</span> Usted puede acceder y ver el contenido del Sitio Web desde su computadora o desde cualquier otro aparato y, a menos de que se indique de otra manera en estos Términos y Condiciones o en el Sitio Web, sacar copias o impresiones individuales del contenido del Sitio Web así como de los archivos descargados para su uso personal, interno únicamente. </li><br>-->
<!--                           <li><span style="font-weight:bold">3. Responsabilidad.</span> Signals CLUB no se hace responsable del mal uso por parte de los usuarios en cuanto a la malversación o timo en conversaciones, análisis y ofrecimientos de ayudas a terceros. Signals CLUB sólo se hará responsable de proporcionar el buen uso de la plataforma y que ésta sea funcional en todo momento.</li><br>-->
<!--                           <li><span style="font-weight:bold">4.Marcas Comerciales.</span> Las marcas comerciales, logos, marcas de servicios, marcas registradas (conjuntamente las "Marcas Comerciales") expuestas en el Sitio Web o en los contenidos disponibles a través del Sitio Web son Marcas Comerciales de Signals CLUB. registradas y no registradas y otras, y no pueden ser usadas con respecto a productos y/o servicios que no estén relacionados, asociados o patrocinados por sus poseedores de derechos y que puedan causar confusión a los clientes, o de alguna manera que denigre o desacredite a sus poseedores de derechos. Todas las Marcas Comerciales que no sean de Signals CLUB. que aparezcan en el sitio Web o en o a través de los servicios del Sitio Web, si las hubiera, son propiedad de sus respectivos dueños. Nada que esté contenido en el Sitio Web deberá ser interpretado como otorgando, por implicación, desestimación, o de otra manera, alguna licencia o derecho para usar alguna Marca Comercial expuesta en el Sitio Web sin el permiso escrito de Signals CLUB. o de terceros que puedan ser dueños de dicha Marca Comercial. El mal uso de las Marcas Comerciales expuestas en el Sitio Web o en o a través de cualquiera de los servicios del Sitio Web está estrictamente prohibido.</li><br>-->
<!--                           <li ><span style="font-weight:bold">5. Información del Usuario.</span> En el curso del uso que usted haga del Sitio Web y/o de los servicios puestos a su disposición en o a través del Sitio Web, se le puede pedir que nos proporcione cierta información personalizada (dicha información en lo sucesivo "Información del Usuario"). Las políticas de uso y recopilación de información de Signals CLUB. con respecto a la privacidad de dicha Información del Usuario se establecen en la Política de Privacidad del Sitio Web, la cual está incorporada al mismo como referencia para todos los propósitos. Usted reconoce y acepta ser el único responsable de la exactitud del contenido de la Información del Usuario.</li><br>-->
<!--                           <li><span style="font-weight:bold">6. Conducta Prohiba del Usuario.</span>Usted garantiza y está de acuerdo en que, mientras use el Sitio Web y los diversos servicios y artículos que se ofrecen en o a través del Sitio Web, usted no: (a) personalizará a ninguna persona o entidad ni desvirtuará su afiliación con alguna otra persona o entidad; (b)  insertará su propio anuncio, posicionamiento de marca o algún otro contenido promocional o el de un tercero  en cualquiera de los contenidos, materiales o servicios o materiales del Sitio Web, ni usará, redistribuirá, republicará o explotará dichos contenidos o servicios con cualquier otro propósito adicional comercial o promocional; ni (c) intentará ganar acceso no autorizado a otros sistemas de cómputo a través del Sitio Web. Usted además no, (i) obtendrá o intentará obtener acceso no autorizado a los sistemas de cómputo, materiales o información por cualquier medio; (ii) usará el Sitio Web o los servicios puestos a su disposición en o a través del Sitio Web de alguna manera con la intención de interrumpir, dañar, deshabilitar, sobrecargar o deteriorar el Sitio Web o dichos servicios, incluyendo, sin limitación, mandar mensajes masivos no solicitados o "inundar" servidores con solicitudes; (iii) usará el Sitio Web o los servicios o artículos del Sitio Web en violación de la propiedad intelectual o de otros derechos legales o patrimoniales de Signals CLUB o de algún tercero; ni (iv) usará el Sitio Web o los servicios del Sitio Web en violación de cualquier ley aplicable. Usted se obliga además, a no intentar (o alentar o apoyar el intento de otro) a embaucar, destruir, decodificar, o de otro modo alterar o interferir con el Sitio Web o con los servicios del Sitio Web, o con cualquier contenido del mismo, o hacer cualquier uso no autorizado del mismo. Usted se obliga a no usar el Sitio Web de alguna manera que pudiera dañar, deshabilitar, sobrecargar o deteriorar el Sitio Web o interferir con que cualquier otra persona pueda usar o disfrutar del Sitio Web o de cualquiera de sus servicios. Usted no obtendrá ni intentará obtener algún material o información a través de cualquier medio que no haya sido estipulado o puesto a la disposición del público intencionalmente a través del Sitio Web.</li><br>-->
<!--                           <li><span style="font-weight:bold">7. Información Privada o Delicada en Foros Públicos.</span> Es importante recordar que los comentarios presentados en un foro pueden ser registrados y almacenados en múltiples lugares, tanto en nuestro Sitio Web como en otra parte en Internet, los cuales pueden ser accesibles durante mucho tiempo y no se tiene control sobre quién los leerá eventualmente. Es por lo tanto importante que tenga usted cuidado y sea selectivo acerca de la información personal que divulgue acerca de usted y de otros, y en especial, no debe divulgar información delicada, patrimonial o confidencial en sus comentarios en nuestros foros públicos.</li><br>-->
<!--                           <li><span style="font-weight:bold">8. Indemnización.</span> Usted se obliga a defender, indemnizar y a sacar a Signals CLUB. y a los directores, funcionarios, empleados y agentes de Signals CLUB. y sus afiliados en paz y a salvo de cualquier demanda, responsabilidad, costos y gastos, de cualquier naturaleza, incluyendo honorarios de abogados, en que incurriera como resultado del uso del Sitio Web, su colocación o transmisión de cualquier mensaje, contenido, información, software u otros materiales a través del Sitio Web, o su incumplimiento o violación de la ley o de estos Términos y Condiciones. Signals CLUB. se reserva el derecho, a su propio costo, de asumir la defensa y control exclusivos de cualquier asunto de otra manera sujeto a indemnización por parte suya, y en dicho caso, usted se obliga a cooperar con Signals CLUB. en la defensa de dicha demanda.</li><br>-->
<!--                           <li><span style="font-weight:bold">9. Señales.</span> Signals CLUB es una plataforma que ofrece a los usuarios la oportunidad de debatir, hablar e informar sobre las diferentes señales del mercado para facilitar o ayudar a orientar a otros usuaios en la compra y venta de criptomonedas. Más Signals CLUB no se hace responsable de que las señales ofrecidas por la propia plataforma, afiliados o usuarios pueden no dar la rentabilidad esperada.</li><br>-->
<!--                           <li><span style="font-weight:bold">10. Sitios Web de Terceros.</span> Usted puede enlazar (link) del Sitio Web a sitios web de terceros y terceros pueden enlazarse al Sitio Web ("Sitios Enlazados"). Usted reconoce y está de acuerdo en que nosotros no tenemos responsabilidad sobre la información, contenido, productos, servicios, anuncios, códigos u otros materiales que puedan o no puedan ser proporcionados por o a través de los Sitios Enlazados, aún si son propiedad de o son dirigidos por afiliados nuestros. Los enlaces (links) a Sitios Enlazados no constituyen un aval o patrocinio nuestro de dichos sitios web o de la información, contenido, productos, servicios, anuncios, códigos u otros materiales presentados en o a través de dichos sitios web.</li><br>-->
<!--                           <li><span style="font-weight:bold">11. Compras.</span> La decisión final de comprar, transferir o cambiar cualquier criptomoneda será responsabilidad del usuario, no pudiendo hacer responsable en ningún momento a la empresa o usuario que ofrecieron “la señal”.</li><br>-->
<!--                           <li><span style="font-weight:bold">12. RENUNCIA DE GARANTÍAS.</span>EL SITIO WEB, INCLUYENDO, SIN LIMITACIÓN, TODOS LOS SERVICIOS, CONTENIDOS, FUNCIONES Y MATERIALES PROPORCIONADOS A TRAVÉS DEL SITIO WEB, SON PROPORCIONADOS "TAL COMO ESTÉN", "COMO SE PONEN A LA DISPOSICIÓN", SIN GARANTÍA DE NINGÚN TIPO, YA SEA EXPRESA O IMPLÍCITA, INCLUYENDO, SIN LIMITACIÓN, CUALQUIER GARANTÍA DE INFORMACIÓN, DATOS, SERVICIOS DE PROCESAMIENTO DE DATOS, ACCESO ILIMITADO O ININTERRUMPIDO, CUALQUIER GARANTÍA CON RESPECTO A LA DISPONIBILIDAD, INTERPRETABILIDAD, NO INTERPRETABILIDAD, EXACTITUD, PRECISIÓN, RECTITUD, PERFECCIÓN, CONCLUSIÓN, UTILIDAD, O CONTENIDO DE LA INFORMACIÓN, Y CUALQUIER GARANTÍA DE TÍTULO, NO-INFRACCIÓN, COMERCIABILIDAD O APTITUD PARA UN PROPÓSITO EN PARTICULAR, Y EN EL PRESENTE RENUNCIAMOS A CUALQUIERA Y A TODAS DICHAS GARANTÍAS, EXPRESAS E IMPLÍCITAS. NO GARANTIZAMOS QUE EL SITIO WEB O LOS SERVICIOS, CONTENIDOS, FUNCIONES O MATERIALES PROPORCIONADOS A TRAVÉS DEL SITIO WEB SEAN OPORTUNOS, SEGUROS, ININTERRUMPIDOS O LIBRES DE ERROR, O QUE LOS DEFECTOS SEAN CORREGIDOS. NO DAMOS GARANTÍA DE QUE EL SITIO WEB O DE QUE LOS SERVICIOS PROPORCIONADOS CUMPLAN CON LOS REQUERIMIENTOS DE LOS USUARIOS. NINGÚN CONSEJO, RESULTADOS O INFORMACIÓN, YA SEA ORAL O ESCRITO, QUE USTED OBTENGA DE NOSOTROS A TRAVÉS DEL SITIO WEB CREARÁ ALGUNA GARANTÍA QUE NO HAYA SIDO ESTABLECIDA EXPRESAMENTE EN EL PRESENTE. Signals CLUB TAMPOCO ASUME NINGUNA RESPONSABILIDAD, Y NO SE HACE RESPONSABLE DE CUALQUIER DAÑO A, O DE CUALQUIER VIRUS QUE PUDIERA INFECTAR SU EQUIPO A CAUSA DE SU ACCESO A, USO DE, O NAVEGACIÓN EN EL SITIO WEB O POR DESCARGAR CUALQUIERA DE LOS MATERIALES, DATOS, TEXTOS, IMÁGENES, CONTENIDOS DE VIDEO O CONTENIDOS DE AUDIO DEL SITIO WEB. SI USTED NO ESTÉ SATISFECHO CON EL SITIO WEB, SU ÚNICA SOLUCIÓN ES DESCONTINUAR USANDO EL SITIO WEB.<br><br>-->
 
<!--TRATAMOS DE ASEGURAR QUE LA INFORMACIÓN PUBLICADA EN EL SITIO WEB ES CORRECTA Y ACTUALIZADA. NOS RESERVAMOS EL DERECHO DE CAMBIAR O HACER CORRECCIONES A CUALQUIER INFORMACIÓN PROPORCIONADA EN EL SITIO WEB EN CUALQUIER MOMENTO Y SIN NINGÚN AVISO PREVIO. Signals CLUB NI AVALA NI ES RESPONSABLE DE LA EXACTITUD O VERACIDAD DE CUALQUIER OPINIÓN, CONSEJO O DECLARACIÓN EN EL SITIO WEB, NI DE CUALQUIER PUBLICACIÓN OFENSIVA, DIFAMATORIA, OBSCENA, INDECENTE, ILEGAL O VIOLATORIA HECHA EN EL MISMO POR CUALQUIER PERSONA A NO SER UN EMPLEADO PORTAVOZ AUTORIZADO DE Signals CLUB. EN SU CARÁCTER OFICIAL (INCLUYENDO, SIN LIMITACIÓN, OTROS USUARIOS DEL SITIO WEB). ES SU RESPONSABILIDAD EVALUAR LA EXACTITUD, CONCLUSIÓN O UTILIDAD DE CUALQUIER INFORMACIÓN, OPINIÓN, CONSEJO U OTRO CONTENIDO DISPONIBLE A TRAVÉS DEL SITIO WEB. </li><br>-->
<!--                           <li><span style="font-weight:bold">13. Leyes Aplicables.</span> Nosotros controlamos y operamos el Sitio Web desde nuestras oficinas ubicadas en México. No representamos a los materiales en el Sitio Web como apropiados o disponibles para su uso en otros lugares. Las personas que escojan acceder al sitio Web desde otros lugares lo harán por su propia iniciativa y son responsables del cumplimiento de las leyes locales, si y al grado en que las leyes locales sean aplicables. Todas las partes sujetas a estos términos y condiciones renuncian a sus derechos respectivos a un juicio con jurado.</li><br>-->
<!--                           <li><span style="font-weight:bold">14. Término.</span> Signals CLUB. puede terminar, cambiar, suspender o descontinuar cualquier aspecto del Sitio Web o de los servicios del Sitio Web en cualquier momento. Signals CLUB. puede restringir, suspender o terminar su acceso al Sitio Web y/o a sus servicios si creemos que usted está en incumplimiento de nuestros términos y condiciones o de la ley aplicable, o por cualquier otra razón sin notificación o responsabilidad. Signals CLUB. mantiene una política que estipula la terminación, en circunstancias apropiadas, de los privilegios de uso del Sitio Web para usuarios que son violadores repetitivos de los derechos de propiedad intelectual.</li><br>-->
<!--                           <li><span style="font-weight:bold">15. Cambios de Términos de Uso.</span> Signals CLUB. se reserva el derecho, a su sola discreción, de cambiar, modificar, añadir o quitar cualquier porción de los Términos y Condiciones, toda o en parte, en cualquier momento. Los cambios en los Términos y Condiciones serán efectivos cuando se publiquen. La continuación del uso del Sitio Web y/o de los servicios puestos a disposición en o a través del Sitio Web después de haber sido publicado cualquier cambio, será considerado como aceptación de esos cambios.</li>-->
<!--                       </ul>-->
<!--                    </p>-->
<!--                    <h5>Estos Términos y Condiciones fueron corregidos el 05/11/2018</h5>-->
                </div>


            </div>
        </div>
    </div>




@endsection